version: '3.7'
services:
  app:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.app
    environment:
      - INGEST_API_KEY=lab-secret
      - REQUIRE_MTLS=true
    networks:
      - socnet

  nginx:
    image: nginx:stable
    ports:
      - "5514:443"
    volumes:
      - ../../deployment/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../certs:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - socnet

networks:
  socnet:
    driver: bridge
